name: Run Preprocessing

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run preprocessing
      run: |
        python preprocessing/automate_mhd-fauzan.py \
          --input_path "personality_dataset.csv" \
          --pipeline_path "preprocessing/preprocess_pipeline.joblib" \
          --output_path "preprocessing/data_test_processing.csv"

    - name: Upload Artifacts (CSV + Pipeline)
      uses: actions/upload-artifact@v4
      with:
        name: hasil-preprocessing
        path: |
          preprocessing/data_test_processing.csv
          preprocessing/preprocess_pipeline.joblib
          preprocessing/preprocess_pipeline_labelencoder.joblib

    - name: Commit and push result back to repo
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add preprocessing/data_test_processing.csv
        git add preprocessing/preprocess_pipeline*.joblib
        git commit -m "Add preprocessed data and pipeline"
        git push
